# **5. Logistic Regression**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
wwcX_train=pd.read_csv('train-test-split\white-win-loss\wwcX_train.csv')
wwcX_test=pd.read_csv('train-test-split\white-win-loss\wwcX_test.csv')
wwcY_train=pd.read_csv('train-test-split\white-win-loss\wwcY_train.csv')
wwcY_test=pd.read_csv('train-test-split\white-win-loss\wwcY_test.csv')

wtcX_train=pd.read_csv('train-test-split\white-termination\wtcX_train.csv')
wtcX_test=pd.read_csv('train-test-split\white-termination\wtcX_test.csv')
wtcY_train=pd.read_csv('train-test-split\white-termination\wtcY_train.csv')
wtcY_test=pd.read_csv('train-test-split\white-termination\wtcY_test.csv')

bwcX_train=pd.read_csv('train-test-split/black-win-loss/bwcX_train.csv')
bwcX_test=pd.read_csv('train-test-split/black-win-loss/bwcX_test.csv')
bwcY_train=pd.read_csv('train-test-split/black-win-loss/bwcY_train.csv')
bwcY_test=pd.read_csv('train-test-split/black-win-loss/bwcY_test.csv')

btcX_train=pd.read_csv('train-test-split/black-termination/btcX_train.csv')
btcX_test=pd.read_csv('train-test-split/black-termination/btcX_test.csv')
btcY_train=pd.read_csv('train-test-split/black-termination/btcY_train.csv')
btcY_test=pd.read_csv('train-test-split/black-termination/btcY_test.csv')

## **White**

### 1) White Win/Loss Classification

In [ ]:
log_wwc=LogisticRegression()

log_wwc.fit(wwcX_train, wwcY_train)
wwcY_pred = log_wwc.predict(wwcX_test)

print("White Win/Loss Classification Report:")
print(classification_report(wwcY_test, wwcY_pred))
print('\n')
print(confusion_matrix(wwcY_test, wwcY_pred))

White Win/Loss Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.67      0.68     79792
           1       0.69      0.71      0.70     82918

    accuracy                           0.69    162710
   macro avg       0.69      0.69      0.69    162710
weighted avg       0.69      0.69      0.69    162710



[[53138 26654]
 [24427 58491]]


### 2) White Termination Classification

In [ ]:
### White Termination Classification
log_wtc = LogisticRegression()
log_wtc.fit(wtcX_train, wtcY_train)
wtcY_pred = log_wtc.predict(wtcX_test)

print("White Termination Classification Report:")
print(classification_report(wtcY_test, wtcY_pred))
print('\n')
print(confusion_matrix(wtcY_test, wtcY_pred))

C:\Users\o\miniconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


White Termination Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.47      0.42     53123
           1       0.40      0.18      0.25     53396
           2       0.49      0.63      0.55     56191

    accuracy                           0.43    162710
   macro avg       0.42      0.43      0.41    162710
weighted avg       0.42      0.43      0.41    162710



[[24950  9705 18468]
 [25171  9607 18618]
 [16133  4672 35386]]


## **Black**

In [ ]:
### Black Win/Loss Classification
log_bwc = LogisticRegression()
log_bwc.fit(bwcX_train, bwcY_train)
bwcY_pred = log_bwc.predict(bwcX_test)

print("Win/Loss Classification Report:")
print(classification_report(bwcY_test, bwcY_pred))
print('\n')
print(confusion_matrix(bwcY_test, bwcY_pred))

### Black Termination Classification
log_btc = LogisticRegression()
log_btc.fit(btcX_train, btcY_train)
btcY_pred = log_btc.predict(btcX_test)

print("Termination Classification Report:")
print(classification_report(btcY_test, btcY_pred))
print('\n')
print(confusion_matrix(btcY_test, btcY_test))

C:\Users\o\miniconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Win/Loss Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.71      0.70     83059
           1       0.69      0.66      0.67     79651

    accuracy                           0.69    162710
   macro avg       0.69      0.68      0.68    162710
weighted avg       0.69      0.69      0.69    162710



[[59002 24057]
 [27129 52522]]


C:\Users\o\miniconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Termination Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.46      0.41     53123
           1       0.40      0.19      0.26     53396
           2       0.49      0.63      0.55     56191

    accuracy                           0.43    162710
   macro avg       0.42      0.43      0.41    162710
weighted avg       0.42      0.43      0.41    162710



[[53123     0     0]
 [    0 53396     0]
 [    0     0 56191]]
